name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    name: build-and-run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code from repository
      uses: actions/checkout@v4
    
    - name: Build Docker images for all microservices
      run: docker compose build
    
    - name: Create environment variables file
      run: |
        echo "MONGODB_AUTH_URI=mongodb://mongodb:27017/auth_service" > .env.test
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test
        echo "MONGODB_PRODUCT_URI=mongodb://mongodb:27017/product_service" >> .env.test
        echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> .env.test
        echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> .env.test
    
    - name: Start all Docker containers
      run: docker compose up -d
    
    - name: Wait for services startup
      run: |
        echo "Waiting for services to be ready..."
        sleep 2
        docker compose ps
  
    # - name: Run unit tests (auth)
    #   run: |
    #     echo "Running auth service tests..."
    
    #     docker exec -e MONGODB_AUTH_URI=mongodb://mongodb:27017/auth_service auth-service npm test
    
    # - name: Run unit tests (product)
    #   run: |
    #     echo "Running product service tests..."
    #     docker exec -e AUTH_SERVICE_URL=http://auth-service:3000 -e PRODUCT_SERVICE_URL=http://product-service:3001 product-service npm test

    - name: Stop and remove containers after testing
      run: docker compose down -v

  deploys:
      name: deploys
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout source code from repository
        uses: actions/checkout@v4
    
      - name: Rebuild Docker images for deployment
        run: docker compose build
    
      - name: Login to Docker Hub registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Tag and push images to Docker Hub
        run: |
          docker tag 22728421-nguyenthanhan-eproject-auth:latest ${{ secrets.DOCKER_USERNAME }}/eproject-auth:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eproject-auth:latest
          docker tag 22728421-nguyenthanhan-eproject-product:latest ${{ secrets.DOCKER_USERNAME }}/eproject-product:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eproject-product:latest
          docker tag 22728421-nguyenthanhan-eproject-order:latest ${{ secrets.DOCKER_USERNAME }}/eproject-order:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eproject-order:latest
          docker 22728421-nguyenthanhan-eproject-api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/eproject-api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eproject-api-gateway:latest
    