name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    name: build-and-run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code from repository
      uses: actions/checkout@v4
    
    - name: Build Docker images for all microservices
      run: docker compose build
    
    - name: Create environment variables file
      run: |
        # AUTH SERVICE
        echo "MONGODB_AUTH_URI=mongodb://mongodb:27017/auth" > auth/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env
        echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> auth/.env
        echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> auth/.env

        # PRODUCT SERVICE
        echo "MONGODB_PRODUCT_URI=mongodb://mongodb:27017/product" > product/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
        echo "RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672" >> product/.env

        # ORDER SERVICE
        echo "MONGODB_ORDER_URI=mongodb://mongodb:27017/order" > order/.env
        echo "RABBITMQ_URI=amqp://rabbitmq:5672" >> order/.env
        echo "RABBITMQ_QUEUE=orders" >> order/.env
        echo "PORT=3002" >> order/.env


    - name: Start all Docker containers
      run: docker compose up -d
    
    - name: Wait for services startup
      run: |
        echo "Waiting for services to be ready..."
        sleep 2
        docker compose ps

    - name: Stop and remove containers after testing
      run: docker compose down -v

  deploys:
    name: deploys
    runs-on: ubuntu-latest
    needs: build-and-run   # CHỈ THÊM DÒNG NÀY
    
    steps:
    - name: Checkout source code from repository
      uses: actions/checkout@v4
    
    - name: Rebuild Docker images for deployment
      run: docker compose build
    
    - name: Login to Docker Hub registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Tag and push images to Docker Hub
      run: |
        docker tag 22728421-nguyenthanhan-eproject-auth:latest ${{ secrets.DOCKER_USERNAME }}/eproject-auth:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/eproject-auth:latest
        docker tag 22728421-nguyenthanhan-eproject-product:latest ${{ secrets.DOCKER_USERNAME }}/eproject-product:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/eproject-product:latest
        docker tag 22728421-nguyenthanhan-eproject-order:latest ${{ secrets.DOCKER_USERNAME }}/eproject-order:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/eproject-order:latest
        docker tag 22728421-nguyenthanhan-eproject-api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/eproject-api-gateway:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/eproject-api-gateway:latest
